on:
  workflow_call:
    inputs:
      translation_directory:
        description: directory babel translations reside in, passed to pybabel compile --directory=...
        required: false
        type: string

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          uv pip install babel build

      - name: Compile translations
        run: |
          if [[ -f setup.cfg ]] && grep -q "compile_catalog" setup.cfg
          then
            python setup.py compile_catalog
          elif [[ -n "${{inputs.translation_directory}}" ]]
          then
            pybabel compile --directory="${{inputs.translation_directory}}" --use-fuzzy
          fi

      - name: Build package
        run: |
          python -m build

      - name: pypi-publish
        uses: pypa/gh-action-pypi-publish@v1.12.4
        with:
          user: __token__
          password: ${{ secrets.pypi_token }}
